version: '3'

services:
  book_catalog:
    image: book_catalog
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://library_db_07jy_user:sbQJ2bDxPELACL7bH3gAXMKLDAlYn79d@dpg-crp2tndds78s73d3ltjg-a.oregon-postgres.render.com/library_db_07jy

  inventory_management:
    image: inventory_management
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management  
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: postgresql://library_db_07jy_user:sbQJ2bDxPELACL7bH3gAXMKLDAlYn79d@dpg-crp2tndds78s73d3ltjg-a.oregon-postgres.render.com/library_db_07jy